spring:
  datasource:
    url: jdbc:${DB_URL}
    #jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    name: CG-BANK

  sql:
    init:
      mode:always